version: '3'

services:
  back-end:
    build: ./Backend/
    volumes: 
      - ./Backend/:/usr/src/app/backend
    ports:
      - 8080:8080
  front-end:
    build: ./Frontend/
    volumes:
      - ./Frontend/:/usr/src/app/
    ports:
      - 8501:8501
    depends_on:
      - back-end
  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    volumes: 
      - cache:/data
volumes:
  cache:
    driver: local  